# Generated by Django 3.2.12 on 2022-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
