# Generated by Django 3.2.12 on 2022-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
