# Generated by Django 3.2.12 on 2022-04-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_training_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actual_presence',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='presence',
            field=models.BooleanField(default=True),
        ),
    ]
