# Generated by Django 3.2.12 on 2022-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20220415_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='actual_presence',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
