# Generated by Django 3.2.12 on 2022-05-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_actual_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deadline'),
        ),
    ]
