# Generated by Django 3.2.13 on 2023-02-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('attendance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendance')),
            ],
        ),
    ]
