# Generated by Django 3.2.13 on 2023-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
