# Generated by Django 3.2.13 on 2023-02-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_training_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.player'),
        ),
    ]
