# Generated by Django 3.2.13 on 2023-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendance_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'permissions': [('verify_training', 'Verify attendance of players that said they would come.')]},
        ),
    ]
