# Generated by Django 3.2.13 on 2023-03-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_training_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='Event',
        ),
    ]
