# Generated by Django 3.2.13 on 2023-03-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('verify_event', 'Verify attendance of players that said they would come.')]},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='training',
            new_name='event',
        ),
    ]
